### ISSUE TITLE
How to handle two different route sets with result of async data request on load with Redux-connected found?

### ISSUE THREAD

**Issue by cymen** [4Catalyzer/found#131]
I converted my app from react-router v2 to found and it's been great. However, I hacked on a feature a while back and haven't figured out how to sensibly bring that over to found:

For most users, I want to use one set of routes. For a specific type of users, I want to use a much smaller set of routes. With react-router v2, I could just fetch the user (Redux-based) and then branch on what routes to render.

With a Redux-connected found, I'm not seeing a good way to do this. I see these options:

* don't create the store so don't use my redux actions/store for the initial user fetch but instead fetch data, then create everything (and can pass fetched data into initial redux store state to avoid duplicate fetch)

* use the happy path for most users but for the special-case users, update the Redux enhance `createMatchEnhancer` with the smaller route set (sounds potentially buggy)

I'm going to go with the first approach for now to unblock myself but I sense I'm missing something obvious so thus this issue.

**Comment by cymen** [comment]
Oh, the other approach I was going to try first was simply making a different bundle for the special-case users. That seems cleanest and is what I'll actually try first.

**Comment by taion** [comment]
It sounds like maybe you're looking for something like https://github.com/4Catalyzer/found/pull/98 (but with e.g. the match context supplied to the custom match function as well). It depends on whether you can determine this condition synchronously.

It's definitely a bit tougher here if you already use a Redux store, since right now changing the routes would require rebuilding the store.

Otherwise, yeah, https://github.com/4Catalyzer/found/issues/104 – probably adding some sort of `reloadRouteConfig` method... somewhere.

**Comment by cymen** [comment]
Yeah, this seems complicated -- I saw both #98 and #104 but couldn't see a way to change the store state for routes after initializing it.

After mulling this over, I think I'll actually go with doing the async data request first and then initialize the store w/ the results and the routes based on the first request. I had thought a separate bundle would be best but there is some complexity there I'd like to avoid too.

It would be great if there was a way to load part of the route tree async -- so basically, you could have a minimal routing set and then load more routes into it based on async data requests. But I don't know how much that complicates things and it's a pretty low-level request so merely mentioning it as possibly a long term way to address this use case.

If that route was of interest, I could see Route taking something like `getChildRoutes` along with the `getComponent` and `getData` props it currently takes. I put the `Child` in there to make it explicit it would only be children routes of the parent route.

**Comment by taion** [comment]
Dynamic child route support would require some pretty invasive changes, so it's not super practical as a near-term thing.

With #104, you'd have something the following, which doesn't look too complicated to me:

```js
const routes1 = // ...;
const routes2 = // ...;

const routeConfig2 = makeRouteConfig(routes2);

const routes = makeRouteConfig(
  <Route
    getData={async () => ({ user: await getUser() })}
    render={({ data, match }) => {
      if (data.user.useRoutes2) {
        match.context.store.found.reloadMatcher(new Matcher(routeConfig2));
        throw new RedirectException(match.location);
      }

      return null;
    }}
  >
    {routes1}
  </Route>
);
```

**Comment by taion** [comment]
Sort of depends how much you care about extra round-trips. The downside of "doing the async data request first" is that you make all the users wait for the extra round-trip.

The proposal I have above would make it so that (potentially) only the users who use `routes2` would need to do a separate data request – not sure how that meets your UX needs.

With some extra complexity it could be possible to e.g. do an initial request + render for both sets of routes in parallel.

**Comment by cymen** [comment]
The funny thing is I actually had to wait anyway on the async request so it hasn't caused a regression in app loading. I refactored so my store is created after I do the async request (and I pass in the data from the async request to as initial state to redux).

This works for now and is easy to reason about and makes sense.

Thank you very much for going over the options with me. I do think async routes would open up some really interesting possibilities but I also get it would be a lot of complexity/change/etc. So this is great for now.

I'll close this issue.

**Comment by taion** [comment]
Okay, fair enough. #98 will land before async routes by a long shot, anyway, though the work is perhaps not so different.

The problem with async routes (dynamic routes in general) is that, since the route objects aren't serializable, we only store the route indices in the Redux store rather than the actual matched routes, which means that we need to traverse through the route config again to figure out the actual routes at render time.

So for the medium term it's going to look more like an explicit route reload, rather than dynamically loading new routes on-the-fly, because it's tricky to avoid breaking Redux tooling otherwise.
