### ISSUE TITLE
Production build

### ISSUE THREAD

**Issue by pbroniarczyk** [4Catalyzer/found#154]
I have a question... I have a probelm with production build of my app. I use Realy Modern with found and I want to make a production build of my React application. The problem is, when i launch my app from a file I got empty screen. Both files (one for all styles and one for app - bundle.js) are correctly bundled and targeting from index.html, but nothin is rendered - my root html element is empty. Is this a found / found-relay problem?

**Comment by taion** [comment]
Do you have any more details?

I guess check that you're including the entry point correctly in your bundle. Otherwise, disable minification and instrument what's actually happening in the entry point.

Is it possible e.g. that your backend isn't responding, or that there are network errors?

**Comment by szmski** [comment]
Hey @taion same problem here, i tried to build your example (@pbroniarczyk as well) from https://github.com/4Catalyzer/found-relay/tree/master/examples/todomvc-modern and there is the same problem we have - blank page, on dev-server is working, but prod version doesn't work :( I'll send you our routes and all dependencies if you want to check this. 

Thanks for your help!

**Comment by taion** [comment]
I tried it and it works just fine.

Since this is routing-driven, it's possible you're trying to open `index.html` directly – that's not going to work because the URL is going to be something like `file:///<whatever>/found-relay/examples/todomvc-modern/build/index.html`, which isn't going to match in the router.

Instead spin up some simple HTTP server to serve the page so the URL is something like `http://localhost:<port>`.
