### ISSUE TITLE
How to access all visited routes since the creation of the router?

### ISSUE THREAD

**Issue by ivosabev** [4Catalyzer/found#200]
I've looked into the code, but couldn't find any public methods exposing the history of the routes visited by the user? 

Basically I need a MemoryProtocol functionality, that also updates the Browser URL.

Any ideas? Thanks!

**Comment by taion** [comment]
Can you elaborate on your use case here? If you need to update the browser URL, why not just use `BrowserProtocol` with the HTML5 history API?

Otherwise, if you just want visited routes, I would add another Redux reducer that takes the dispatched `@@farce/UPDATE_LOCATION` and does whatever it needs here.

**Comment by ivosabev** [comment]
The use case is that I need all locations accessed by the user, since he started using our application.

Could you provide some sample code how to add the reduce and access its values? Thanks!

**Comment by taion** [comment]
How does that connect to updating the URL, though? If you just need to update the URL, then you shouldn't need a "history" –  the current location gives you enough.

In any event, you'd do this by installing a reducer along these lines: https://github.com/4Catalyzer/found/blob/master/src/foundReducer.js (`UPDATE_MATCH` is probably the action you want), and then in the reducer just append `payload.location` to an array or something equivalent.

See the "connected router" guide in the README for how to set up a router with a custom Redux store.
