### ISSUE TITLE
`RESOLVE_MATCH` is not emitted initially

### ISSUE THREAD

**Issue by catamphetamine** [4Catalyzer/found#202]
When running `universal-redux` example there's a bug: `RESOLVE_MATCH` is not emitted initially after `UPDATE_MATCH`.

**Comment by catamphetamine** [comment]
Possible cause:

```js
    componentDidMount() {
      if (!this.props.initialRenderArgs) {
        this.resolveMatch();
      }
```

For some reason it doesn't emit it if `initialRenderArgs` are passed.
Still it executes all `getData` functions.
@taion What is the way to know on client when all `getData` functions are resolved on initial page load?

**Comment by catamphetamine** [comment]
`getData` seems to only be called from `resolver.resolveElements`.
Which means that `resolver.resolveElements` is somehow called during the initial page render on client.
The only place where `resolver.resolveElements` is called is `resolveRenderArgs`.
The only places where `resolveRenderArgs` are called are `createBaseRouter` where it doesn't get called and `getRenderArgs` which is called in `getStoreRenderArgs`.
`getStoreRenderArgs` is called in `universal-redux/src/client.js` which means I can add a manual `dispatch()` there and emit any action there.
This solves my use case.

**Comment by taion** [comment]
That would trigger an extra re-render. `RESOLVE_MATCH` isn't quite meant to communicate that the `getData` calls have finished – more that no more components are in a "pending" state. If you need to trigger that, I'd suggest extending the resolver and dispatching an action when the resolver finishes.

**Comment by catamphetamine** [comment]
@taion Don't you find it inconvenient and really irrational that `getData` for all routes are run when navigation happens?
For example, the user goes from `/pages/a` to `/pages/b` and `getData` is run for:

* `/`
* `pages`
* `b`

While `getData` should be run for `b` in this case the other two are unnecessary because they have been already loaded for `/pages/a`.

**Comment by taion** [comment]
It's consistent with how `getDerivedStateFromProps` works.

You can always add your own caching via e.g. Redux. If on the other hand the router forcibly caches data, then there's no way around that.

**Comment by barberdt** [comment]
@taion related question.

I have a resource id that is captured as a query param, let's call id `?fooId=123`. I have a need to cache this id in Redux (it's used in many many shared places in many many complex ways such that referencing it from React context or passing it through from the route handler's `location` prop is not feasible). Listening to `RESOLVE_MATCH` to grab that id and cache it in Redux is ideal. `UPDATE_MATCH` happens prematurely (before the app tree re-renders as a part of the navigation). However, the lack of `RESOLVE_MATCH` on initial page load makes this a non-starter.

"RESOLVE_MATCH isn't quite meant to communicate that the getData calls have finished – more that no more components are in a "pending" state"

Are components never considered to be in a "pending" state on the initial page load?

Thanks!

**Comment by barberdt** [comment]
@taion sort of related.

Let's suppose I have integrated the router with my existing Redux setup. Let's then say there are certain values derived from query params that I would like to cache in my Redux store. When those query params change, I would like to update those derived values in my Redux store. If I rely on `UPDATE_MATCH`, updating those values will cause any connected React components to update prematurely (i.e. before the router has resolved the match). This needs to be avoided. Enter `RESOLVE_MATCH`. Listening to `RESOLVE_MATCH` to then update those derived values works exactly as expected. It ensures the router has resolved the match and that there won't be any premature React updates when I change those derived values.

There's only one catch. `RESOLVE_MATCH` doesn't fire on the initial page load. It is important that these derived values get computed on the initial page load. Is it assumed that I am to listen to `UPDATE_MATCH` just the once during initial page load and then swap to listening to `RESOLVE_MATCH` from that point forward?

I guess I'm not sure why we don't also fire `RESOLVE_MATCH` on the initial page load. After all, we are setting the `resolvedMatch` field in Redux at the same time `UPDATE_MATCH` gets handled.

Thanks!

**Comment by taion** [comment]
Sorry for the delayed response here. The technical reason why we don't fire `RESOLVE_MATCH` on the initial page load is because the resolution comes from a different code path. The data loading itself isn't done in Redux, because in general the loaded data may not be serializable (or even live in Redux), which means we need an external hook from the router itself to notify the store that the match is actually resolved.

So in that sense, the match isn't _actually_ resolved yet on the initial page load, because we haven't done all the data fetching yet, and are still rendering preliminary results. It's just that, in this case, we don't need the extra re-render. Also, given where `RESOLVE_MATCH` gets fired, it'd never come up in the server rendering case.

I think it might be possible with a bit of work to fix some of this and actually fire `RESOLVE_MATCH` for an initial client render, but I'm not sure it's worthwhile, or that it e.g. makes sense in a full SSR-style case where this initial resolution isn't even happening.

As you've noticed, I deal with it in https://github.com/4Catalyzer/found/blob/ca594e7d1800ac7d45ab6e82fd1a7b994945c964/src/foundReducer.js by checking to see whether we already have a `resolvedMatch`, and treating `UPDATE_MATCH` as `RESOLVE_MATCH` if there isn't already one. So in that case, yeah, you'd listen to both. The code then should look something like:

```js
function myReducer(state = null, action) {
  const { type, payload } = action;

  if (
    (type === ActionTypes.UPDATE_MATCH && !state) ||
    type === ActionTypes.RESOLVE_MATCH
  ) {
    return doSomething();
  }

  return state;
}
```

**Comment by barberdt** [comment]
@taion no problem at all. Thanks for the reply!

The technical explanation makes total sense and is what I understood to be the case. I am handling my needs to derive state on the initial page load in the exact same way you have suggested here. It's not difficult and as long as it's the assumed way to handle that case, I have no issue with it. Happy to confirm I'm not doing something out of the ordinary.

Thanks!
