### ISSUE TITLE
Support for multiple routers

### ISSUE THREAD

**Issue by harryy2510** [4Catalyzer/found#227]
I tried creating multiple routers with different route config. I got it working somehow but it fails on page refresh.

Here's the link: [CodeSandbox](https://codesandbox.io/s/zk8n85k2v3)

### Steps to reproduce:
1. Click on child
2. Click on foo
3. Refresh

**Comment by taion** [comment]
In general, you shouldn't need multiple routers. If you're embedding multiple routed child components, it will most likely work better to use the named child route support per https://github.com/4Catalyzer/found#named-child-routes.

Otherwise, if you're using multiple routers, the tricky part is that actions live in a flat namespace. For now, you'd most likely have to set up two Redux stores.

**Comment by harryy2510** [comment]
If you can help me with my usecase, I'll try to explain what I am actually trying to achieve.

My project is a monorepo with multiple packages with their own route configuration. Main app component also has a route configuration which basically lazyloads packages based on routing. Once navigated to a package, further nested routes are handled by the package itself.


For Example:
1. /package1 is handled by Main app
2. /package1/listitem1 is handled by Package1

**Comment by taion** [comment]
To make your case work, use `replaceRouteConfig` per https://github.com/4Catalyzer/found#hot-reloading to add in the routes for each of the sub-packages on load.

Because of the middleware setup via the Redux store, we can't really support setting up multiple routers well, but you can update route configs as you go, and per the mechanism above, merge in new routes for the sub-packages as needed.
