### ISSUE TITLE
Re-route when a specific redux store entry changes

### ISSUE THREAD

**Issue by UFOMelkor** [4Catalyzer/found#380]
Hey,

I have some custom Routes, e.g. one that looks in the redux state whether the visitor is logged in and throws an HttpError if not.

This works pretty well, but I'm curious: Is it possible to automatically let the router re-render the current URL if a specific state changes? Currently, I manually dispatch a `go(0)` to force a re-routing every time I change the specific state.

**Comment by taion** [comment]
Triggering a navigation essentially requires dispatching an action. It's a little bit un-idiomatic in Redux to dispatch actions in response to store changes, though any mechanism available there will technically work.

A more idiomatic approach might be to set up a middleware that will dispatch the appropriate actions on other Redux _actions_, rather than on store changes.

**Comment by UFOMelkor** [comment]
Thank you, that is what I do currently :-) :+1:
