### ISSUE TITLE
next.js

### ISSUE THREAD

**Issue by steida** [4Catalyzer/found#41]
Is it possible to create the same DX as zeit/next.js on top of the found?

**Comment by taion** [comment]
Sure – the idea would be that you generate your route config on-the-fly (maybe at build time?) by looking at the files in the `pages/` directory. Like you could just do some codegen for the routes, then run it through webpack.

It's a bit out of scope for the core `found` package specifically since it assumes a lot of build tooling – more importantly I think it also makes you lose the power of nested routes + the associated data fetching stuff there, which is not ideal.

Like the "free" component prefetching is pretty cool and I'm planning on playing around with adding that, but at some level the application still needs to display feedback if the user clicks on a link and the remote component/data aren't available yet – and the choice of what to display is an application-level thing.
