### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by jepezi** [4Catalyzer/found#46]
Hi Jimmy!

I've been following and using tools you have written/maintained, react-router, react-router-relay and now that I see found. Really like the rationale about found and what it aims to solve. I'm sure there are people like me who never got the chance to say this. So just wanna drop by and say THANK YOU for your work.

About found, please let me know if I could help on anything on your to-do list or roadmap.

**Comment by taion** [comment]
Thanks! I'm just working to figure out a few API things right now. I'm tracking the issues on the issue tracker that I've thought of so far, but a lot of them aren't actionable yet.

**Comment by satazor** [comment]
As an alternative to the path that rr4 is taking, this module looks promising.

@taion could you share the status of this package? Is there any missing stuff? I'm mostly worried about it not being 1.0.0 yet which kind of implies the API is not finished yet.

**Comment by taion** [comment]
@satazor 

The only user-facing API change coming up is that I'm going to change the imports for JSX route definitions a bit (it will be e.g. `found/lib/Route` and `found/lib/Redirect` rather than `found/lib/jsx/Route` and `found/lib/jsx/Redirect`).

I'm going to change around the internal API for element resolution a little bit to make it easier to tear things down when leaving routes, but that will not be user-facing in most cases.

Otherwise, I just want to be a bit conservative – I'd really like a few people to tell me ways in which the API is painful/awful, because I don't want to say that I've gotten things right on the initial revision.

**Comment by taion** [comment]
Thanks to all of you (: I'm going to close this issue to clean up the list of things we're tracking.
