### ISSUE TITLE
getData vs. colocation

### ISSUE THREAD

**Issue by jepezi** [4Catalyzer/found#62]
I really like the design of found to load data and component in parallel. However, there is a nice thing about data dependency colocated with component. Now, I'm wondering if there is a found way to colocate the data dependencies in component when doing code splitting?

Specific code from docs to illustrate the question.

```js
<Route
      path="/"
      Component={AppPage}
    >
      <Route
        Component={MainPage}
      />
      <Route
        path="widgets"
      >
        <Route
          Component={WidgetsPage}
          getData={fetchWidgets}
        />
        <Route
          path="widgets/:widgetId"
          getComponent={() => (
            System.import('./WidgetPage').then(module => module.default)
          )}
          getData={({ params: { widgetId } }) => (  /* <------------------------- getData here
            fetchWidget(widgetId).catch(() => { throw new HttpError(404); })
          )}
```

From the sample code above, getData function can not be inside WidgetPage if you don't want waterfall. In other words, how does found-relay solve this?

**Comment by taion** [comment]
Found Relay reimplements the element resolver to first resolve all components, then dispatch all data requirements in sync. We have to do it this way to work with Relay 1, which doesn't have a way to split out data requirements.

In general, this sort of data colocation incurs the cost of not allowing dispatching the data request until the component is loaded. In the case where the code for fetching your data is not large, it's probably better to inline it into your entry chunk.

If you want to use e.g. a static method on the component class, you could await `getComponent` yourself in `getData`, then call the static method. I don't do this with Found Relay because I want full batching of Relay data requests, but probably this is less of an issue if you're querying a REST API.

**Comment by jepezi** [comment]
@taion Thanks for the reply. 

> Found Relay reimplements the element resolver to first resolve all components, then dispatch all data requirements in sync.

Is it your intention to design `Found` (and `Found Relay`) to pave the way for Relay 2's static queries to solve this problem?

**Comment by taion** [comment]
Exactly. Once Relay 2 lands, I want to inline all the queries into my entry chunk, and fetch code and data in parallel, per https://github.com/facebook/relay/issues/1317.

**Comment by jepezi** [comment]
Awesome! Will keep an eye on this. Btw, Found's server-render API is very clean. Totally love it.
