### ISSUE TITLE
Rendering of ancestor routes broken on 0.4?

### ISSUE THREAD

**Issue by dmwallace** [4Catalyzer/found#620]
Minimal reproducible example:

`import createBrowserRouter from 'found/lib/createBrowserRouter';
import React from 'react';
import ReactDOM from 'react-dom';

const routes = [
	{
		path: '/',
		Component: (props) => <div><p>/</p>{props.children}</div>,
		children: [
			{
				path: '/parent',
				Component: (props) => <div><p>/parent</p>{props.children}</div>,
				children: [
					{
						path: '/child',
						Component: (props) => <div><p>/child</p></div>
					}
				]
			}
		],
		
	},
]

const BrowserRouter = createBrowserRouter({ routeConfig: routes });

ReactDOM.render(<BrowserRouter/>, document.getElementById('root'));`

All routes render correctly on version 0.3.x, but on 0.4.x only /parent/child renders anything.  /parent and / won't render as long as they have child routes.  If you take the child routes out they render correctly.

**Comment by taion** [comment]
This was an intentional change per https://github.com/4Catalyzer/found/releases/tag/v0.4.0 (https://github.com/4Catalyzer/found/pull/217), as it was otherwise not possible to get e.g. `/parent` to _not_ match.

If you still need a non-leaf route to match, just add some stub leaf child to it, e.g. just an empty object.
