### ISSUE TITLE
Is is possible to add route config (matching url) dynamically?

### ISSUE THREAD

**Issue by jacobbubu** [4Catalyzer/found#81]
React Router has a example to show its dynamic routing capability at https://reacttraining.com/react-router/web/example/recursive-paths.  How could I implement it using found?

**Comment by taion** [comment]
For something like recursive paths, you'd want to use repeated groups in path-to-regexp, and just handle the rendering yourself.

If you want to update the route config on-the-fly, I'd be happy to take API proposals. We don't have a way to do that right now, because route configs can't live in the Redux store (they're not JSON serializable), and currently we need to close over them.

**Comment by jacobbubu** [comment]
Understood, thanks for the reply.
